name: Basic CI

on:
  push:
    branches: 
      - main
      - cicd
  pull_request:
    branches:
      - main
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Specify the Python version you are using

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run your unit tests
    - name: Run Tests
      run: python -m unittest discover

    - name: Setup Backend Environment
      run: echo "Backend setup will go here"

